import com.progressoft.Interface1;
import com.progressoft.Interface10;
import com.progressoft.Interface2;
import com.progressoft.Interface3;
import com.progressoft.Interface4;
import com.progressoft.Interface5;
import com.progressoft.Interface6;
import com.progressoft.Interface7;
import com.progressoft.Interface8;
import com.progressoft.Interface9;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'u259' at '1/2/17 10:51 PM' with Gradle 2.14.1
 *
 * @author u259, @date 1/2/17 10:51 PM
 */
public class Library implements Interface1,Interface2,Interface3,Interface4,Interface5,Interface6,Interface7,Interface8,Interface9,Interface10{
    public boolean someLibraryMethod() {
    	System.out.println("what a nice code");
        return true;
    }
}
