/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'u259' at '1/2/17 10:51 PM' with Gradle 2.14.1
 *
 * @author u259, @date 1/2/17 10:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("what a nice code");
    	System.out.println("re test me again pl....");
    	
        return true;
    }
}
